name: Publish container
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12.7...
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.7
      id: go
    - name: Checkout master...
      uses: actions/checkout@master
      id: checkout
    - name: Get dependencies...
      run: go mod download
    - name: Run tests...
      run: go test -v ./...
    - name: Logging in to container registry...
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Building Docker image...
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      run:
        docker build --rm -t $DOCKER_IMAGE:$(echo ${GITHUB_SHA} | head -c7) .
    - name: Publishing image...
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      run: docker push $DOCKER_IMAGE:$(echo ${GITHUB_SHA} | head -c7)
